src/Entity/Blocks/Block.php
<?php
/**
 * @author Nathan JANCZEWSKI <nathan@janczewski.fr>
 */

namespace App\Entity\Blocks;

use App\Services\FakePath;
use App\Traits\IDTrait;
use App\Traits\OrderTrait;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity
 * @ORM\Table(name="Block")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 */
abstract class Block
{

    use IDTrait, OrderTrait;

    public abstract function getBlockType(): string;

    public abstract function getBlockTypeName(): string;

    public abstract function getParameters(FakePath $fp, EntityManagerInterface $emi): array;

}

src/Entity/News.php
<?php
/**
 * @author Nathan JANCZEWSKI <nathan@janczewski.fr>
 */

namespace App\Entity;
use App\Traits\IDTrait;
use App\Traits\SlugTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 * @ORM\Table(name="News")
 */
class News
{
    use IDTrait, SlugTrait;

    /**
     * @ORM\Column(type="string", length=30)
     */
    protected $title_fr;

    /**
     * @ORM\Column(type="string", length=30)
     */
    protected $title_en;

    /**
     * @ORM\Column(type="text")
     */
    protected $content_fr;

    /**
     * @ORM\Column(type="text")
     */
    protected $content_en;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $creationDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $writer;

    public function getTitleFR()
    {
        return $this->title_fr;
    }

    public function setTitleFR($title_fr)
    {
        $this->title_fr = $title_fr;
        return $this;
    }

    public function getTitleEN()
    {
        return $this->title_en;
    }

    public function setTitleEN($title_en)
    {
        $this->title_en = $title_en;
        return $this;
    }

    public function getContentFR()
    {
        return $this->content_fr;
    }

    public function setContentFR($content_fr)
    {
        $this->content_fr = $content_fr;
        return $this;
    }

    public function getContentEN()
    {
        return $this->content_en;
    }

    public function setContentEN($content_en)
    {
        $this->content_en = $content_en;
        return $this;
    }

    public function getCreationDate()
    {
        return $this->creationDate;
    }

    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;
        return $this;
    }

    public function getWriter()
    {
        return $this->writer;
    }

    public function setWriter($writer)
    {
        $this->writer = $writer;
        return $this;
    }

}

src/Entity/PseudoEntity/BandMenuItem.php
<?php
/**
 * @author Nathan JANCZEWSKI <nathan@janczewski.fr>
 */

namespace App\Entity\PseudoEntity;

use App\Entity\Page;
use App\Traits\IDTrait;
use App\Traits\OrderTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="bandmenu_item")
 */
class BandMenuItem
{

    use IDTrait, OrderTrait;

    /**
     * @ORM\Column(type="text", length=30)
     */
    private $text_fr;

    /**
     * @ORM\Column(type="text", length=30)
     */
    private $text_en;

    /**
     * @ORM\Column(type="text", length=20)
     */
    private $icon_name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PseudoEntity\BandMenu", inversedBy="menuItems")
     * @ORM\JoinColumn(name="menu_id", referencedColumnName="id")
     */
    private $menu;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Page")
     * @ORM\JoinColumn(name="dest", referencedColumnName="id", onDelete="CASCADE")
     */
    private $dest;

    public function getTextFr(): string
    {
        return $this->text_fr;
    }

    public function setTextFr($text_fr): BandMenuItem
    {
        $this->text_fr = $text_fr;
        return $this;
    }

    public function getTextEn(): string
    {
        return $this->text_en;
    }

    public function setTextEn($text_en): BandMenuItem
    {
        $this->text_en = $text_en;
        return $this;
    }

    public function getIconName(): string
    {
        return $this->icon_name;
    }

    public function setIconName($icon_name): BandMenuItem
    {
        $this->icon_name = $icon_name;
        return $this;
    }

    public function getMenu(): BandMenu
    {
        return $this->menu;
    }

    public function setMenu($menu): BandMenuItem
    {
        $this->menu = $menu;
        return $this;
    }

    public function getDestination(): Page
    {
        return $this->dest;
    }

    public function setDestination(Page $dest): BandMenuItem
    {
        $this->dest = $dest;
        return $this;
    }

}

templates/base.html.twig
{# The page var is defined in children pages to set the selected item in the menu #}
{% set pageName = pageName|default('none') %}

{# Just a simple macro to create a menu item #}
{% macro menuitem(text, link, pagename, currPage) %}
    <li class="{{ currPage == pagename ? "selected" : "" }}"><a href="{{ link }}">{{ text }}</a></li>
{% endmacro %}

{# For some reason we are forced to import it even though it's defined here.. #}
{% import _self as macros %}

<!DOCTYPE html>
<html xmlns:og="http://ogp.me/ns#">
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/base.css') }}" />
    {% block stylesheets %}{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <div class="top">
        <img src="{{ asset('assets/images/logo.png') }}">
    </div>
    <nav>
        <ul>
            {% for menuItem in MainMenuFetcherService.MainMenu %}
                {{ macros.menuitem(menuItem.textFr, path('display_page', {'page': menuItem.destination.slug}), menuItem.destination.slug, pageName) }}
            {% endfor %}
        </ul>
    </nav>
</header>
<div class="body">
    {% block body %}{% endblock %}
</div>

<script src="{{ asset('assets/runtime.js') }}"></script>
<script src="{{ asset('assets/base.js') }}"></script>

{% if (ConfigService.getConfig("footer", "false").value == "true") %}
<footer>
    <div id="copyright"><div>Copyright 2018-2019 Overflow</div><div>Tous droits réservés</div></div>
    <div id="user_login" class="not-first-nor-last">
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            <div>
                {{ 'layout.logged_in_as'|trans({'%username%': app.user.username}, 'FOSUserBundle') }}
            </div>
            <div>
                {% if is_granted("ROLE_ADMIN") %}
                    <a href="{{ path("admin_index") }}">Administration</a> |
                {% endif %}
                <a href="{{ path('fos_user_security_logout') }}">
                    {{ 'layout.logout'|trans({}, 'FOSUserBundle') }}
                </a>
            </div>
        {% else %}
            <a href="{{ path('fos_user_security_login') }}">{{ 'layout.login'|trans({}, 'FOSUserBundle') }}</a>
        {% endif %}
    </div>
    <div id="legals" class="last"><a href="#">Mentions Légales</a></div>
</footer>
{% endif %}
{% block javascripts %}{% endblock %}
</body>
</html>

templates/news.html.twig
{% extends "base.html.twig" %}
{% set pageName = news.slug %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('assets/page_one_news.css')}}" />

    <meta property="og:title" content="{{ news.titleFR }}" />
    <meta property="og:type" content="article" />
    {% set configSiteURL = ConfigService.getConfig("site_url", "none") %}
    {% if (configSiteURL.value != 'none') %}
        <meta property="og:url" content="{{ configSiteURL.value ~ path('display_news', {'slug': news.slug}) }}" />
    {% endif %}
{% endblock %}

{% block body %}

    <h1>{{ news.titleFR }}</h1>

    <p>{{ news.contentFR }}</p>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/page_one_news.js') }}"></script>
{% endblock %}

templates/page.html.twig
{% extends "base.html.twig" %}
{% set pageName = page.slug %}
{% set blocktype = []  %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('assets/page_' ~ pageName ~ '.css')}}" />
    {% for block in page.blocks %}
        {% if block.blockType|lower not in blocktype %}
            <link rel="stylesheet" type="text/css" href="{{asset('assets/blocks/' ~ block.blockType|lower ~ '_css.css')}}" />
            {% set blocktype = blocktype|merge([block.blockType|lower]) %}
        {% endif %}
    {% endfor %}
    {% set blocktype = [] %}
{% endblock %}

{% block body %}
    {% for block in page.blocks %}
        {{ BlockRendererService.getHTML(block, fakepath)|raw }}
    {% endfor %}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/page_' ~ pageName ~ '.js') }}"></script>
    {% for block in page.blocks %}
        {% if block.blockType|lower not in blocktype %}
            <script src="{{ asset('assets/blocks/' ~ block.blockType|lower ~ '_js.js') }}"></script>
            {% set blocktype = blocktype|merge([block.blockType|lower]) %}
        {% endif %}
    {% endfor %}
{% endblock %}

templates/quillbox.html.twig
{% macro quillbox(id, toolbarID, contentID) %}
    <div class="quillbox" id="{{ id }}">
        <div id="{{ toolbarID }}">
            <span class="ql-formats">
              <select class="ql-font"></select>
              <select class="ql-size"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-bold"></button>
              <button class="ql-italic"></button>
              <button class="ql-underline"></button>
              <button class="ql-strike"></button>
            </span>
            <span class="ql-formats">
              <select class="ql-color"></select>
              <select class="ql-background"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-script" value="sub"></button>
              <button class="ql-script" value="super"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-header" value="1"></button>
              <button class="ql-header" value="2"></button>
              <button class="ql-blockquote"></button>
              {#<button class="ql-code-block"></button>#}
            </span>
            <span class="ql-formats">
              <button class="ql-list" value="ordered"></button>
              <button class="ql-list" value="bullet"></button>
              <button class="ql-indent" value="-1"></button>
              <button class="ql-indent" value="+1"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-direction" value="rtl"></button>
              <select class="ql-align"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-link"></button>
              <button class="ql-image"></button>
              <button class="ql-video"></button>
              <button class="ql-formula"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-clean"></button>
            </span>
        </div>
        <div id="{{ contentID }}">
        </div>
    </div>
{% endmacro %}